apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-api
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-api
  template:
    metadata:
      labels:
        app: nestjs-api
    spec:
      containers:
        - name: nestjs-api
          image: pajjaphon/nestjs-api:3c3a53fa7d36a3d30633225835ff099e75057431
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: nestjs-api-config
          # livenessProbe:
          #   httpGet:
          #     path: /api/v1/health
          #     port: 5000
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /api/v1/health
          #     port: 5000
          #   initialDelaySeconds: 5
          #   periodSeconds: 20
          resources:
            requests:
              cpu: '0.25'
              memory: 128Mi
            limits:
              cpu: '0.5'
              memory: 256Mi
